import RoundComponent from "@/components/round";
import { getGoogleSheetData } from "@/services/googleSheetService";
import { Round } from "@/types/Round";
import {
  HydrationBoundary,
  QueryClient,
  dehydrate,
  useQuery,
} from "@tanstack/react-query";
import axios from "axios";
import type { sheets_v4 } from "googleapis";
import { type InferGetServerSidePropsType } from "next";
import Head from "next/head";
import Link from "next/link";

const intervalMs = 5 * 1000;

export async function getServerSideProps() {
  const queryClient = new QueryClient();

  await queryClient.prefetchQuery({
    queryKey: ["swiss-rounds"],
    queryFn: async () => await getGoogleSheetData(),
  });

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
}

export default function Home({
  dehydratedState,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  const { data } = useQuery({
    queryKey: ["swiss-rounds"],
    queryFn: async () => {
      const response =
        await axios.get<Round[]>(
          "/api/googleSheet",
        );
      return response.data;
    },
    // refetchInterval: intervalMs,
  });

  return (
    <HydrationBoundary state={dehydratedState}>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col justify-center bg-hero-pattern bg-cover bg-repeat-round">
        <div className="flex flex-row gap-12 py-16 ">
          <div className="flex w-full justify-center gap-5 px-5">
            <RoundComponent />
            <RoundComponent />
            <RoundComponent />
            <RoundComponent />
            <RoundComponent />
            <RoundComponent />
          </div>
        </div>
      </main>
    </HydrationBoundary>
  );
}
